### ISSUE TITLE
make offer conditional fields

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#104]
The following sections are required depending on the offer that is being made. We need a way of ensuring they are filled in if they need to be, and empty if they are not.

Equipment rental and all associated fields

Box rental and all associated fields

@jonscottfilm is there anything else to add here? are both the above 'topics' the only conditional requirements?

**Comment by JMurphyWeb** [comment]
implementation for now:

Equipment rental & box rental checkboxes

Checking the checkbox suggests the associated fields are required. Unchecked box suggests they are not. 

As a future enhancement we can remove the fields until the PM checks the checkbox, but for now UI will remain static.

**Comment by jonscottfilm** [comment]
This was discussed in #12 

_'Hey Jack. Brace yourself...

Most required (R), i.e. essential),
some conditional & required (CR)
some calculated (C),
some to delete (D),
some optional (O).
Oh, and NEW field (N) :-)

target_email:string
user_id:references:users
project_id:references:projects
department:string (R)
job_title:string (R)
start_date:date (R)
daily_or_weekly:string (R)
working_week:float (R)
currency:string (R)
overtime_rate_per_hour:integer (D)
other_deal_provisions:text (O)
box_rental_fee_per_week:integer (R, default value is 0.00)
box_rental_description:string (CR, subject to 'more than 0.00' answer to box
_rental_fee_per_week: integer)
box_rental_cap:integer (CR)
box_rental_period:string (CR)

equipment_rental_fee_per_week:integer (R, default value is 0.00)
equipment_rental_description:string (CR, subject to 'more than 0.00' answer
to equipment_rental_fee_per_week: integer)
equipment_rental_cap:integer (CR)
equipment_rental_period:string (CR)
vehicle_allowance_per_week:integer (R, default value is 0.00)
fee_per_day_inc_holiday:integer (R)
holiday_pay_per_day:integer (C)
holiday_pay_per_week:integer (C)
sixth_day_fee:float (C)
seventh_day_fee:float (C)
additional_notes:text (O)
contractor_details_accepted:boolean'_

**Comment by JMurphyWeb** [comment]
@jonscottfilm thanks. So my original assessment was ok.. how about the checkbox implementation?

**Comment by jonscottfilm** [comment]
let me test

_Optional_ items for the offer are:
Box Rental
Equipment Rental
Vehicle Allowance

The original method was a way to MAKE the PM fill in the fields, and not skip over something he forgot to finalise in the deal phonecall...    So the thinking was: anything more than zero (move the field up in appearance order) in eg Box Rental rate, makes the additional fields required.

It would be **cleaner** to have a YES/NO **required** dropdown, no default selected, for the optional item, and then then reveal/un-grey/make required, the additional fields...

Otherwise, he can still skip over a pre-filled no, or zero value - and forget to enter it.

**Comment by JMurphyWeb** [comment]
vehicle allowance defaults to 0.  I have added checkboxes for the box rental and equipment rental fields.

The form doesn't change but the backend requirements (what is really important right now) do.

**Comment by JMurphyWeb** [comment]
@jonscottfilm its in review.
