### ISSUE TITLE
startpack - basic changeset for definitely required fields

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#138]
There are a some fields in the startpack that are required regardless of any conditions in the project or the offer.

I am currently working out what they are from the spreadsheet

linked to #132

```

date_of_birth
place_of_birth
gender
screen_credit_name
country_of_legal_nationality
country_of_permanent_residence

mobile_tel
primary_address_1
primary_address_city
primary_address_postcode
primary_address_country

passport_number
passport_expiry_date
passport_issuing_country
passport_full_name
passport_url

agent_deal?

student_loan_not_repayed?

emergency_contact_name
emergency_contact_relationship
emergency_contact_tel

bank_name
bank_address
bank_account_users_full_name
bank_account_number
bank_sort_code
```

**Comment by JMurphyWeb** [comment]
Removed these fields as they are always going to be on the user table:
```
first_name
last_name
email

```

**Comment by JMurphyWeb** [comment]
This can be tested by leaving one of the [required fields](https://github.com/karmaradio/karma/issues/138#issue-231074904) blank  in the and the contractor should not be able to accept the offer.

**Comment by jonscottfilm** [comment]
OK, wtf. Help. I'm going around in circles trying to find out what fields are required in order to accept an offer... :)

eg, this offer/startpack (created by jonscottfilm@gmail.com, sent to jonscottfilm@yahoo.co.uk)
https://karmaradio.herokuapp.com/startpack?offer_id=19

**Various reasons why this is tricky (now, albeit testing):**

1. there is no guidance as to what fields are required in relation to the deal
2. offers in the offer view aren't labelled with the project they are from
3. revision date/time
4. project details aren't included at the top of the offer
5. no error message indicating which fields are required _in order to complete the startpack_ per that offer

I know there'll be reasons, it's just making it somewhat challenging. :)

**Comment by jonscottfilm** [comment]
Working. Closing! End of Sp2!! Well done everybody!

I'm creating few issues relating to 'start pack validation - contract type related fields' #201 - none of which appear to be working.
