### ISSUE TITLE
[COMPLETED] Signing: PM can add signees to a project

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#393]
As a PM, 
I can add signees to a project, 
so that they appear in the dropdown when adding a signee to a specific document's approval chain.

Linked to #387

Signees table:
name,
role,
email,
project_id

**Comment by jonscottfilm** [comment]
Seems to work well. Minor design comments:

When a PM has not added any signees yet, the 'Add signee box', and banner 'You haven't added any signees to the project yet' are _touching_.

![image](https://user-images.githubusercontent.com/28431542/27383022-06c3604c-5681-11e7-9da7-cc5c56b1349e.png)

At the same time, we should make the dotted line of the above 'add documents', the same solid style as the 'add signee' box.

Also, Becca (:)) is not sure if the word 'signee' is correct, rather than Signatory (bit too much), Signer, or Approver...? 

Happy to create new issues if you prefer me to.

**Comment by jonscottfilm** [comment]
It might be worth making it harder to delete a project signee. Just wondering what happens to a document in transit around the approval chain, if someone is removed? Maybe just an 'are you sure?' warning.

You can add the same person (email address) as a signee, more than once. Consequences are not disastrous, but feel it should have an error: 'you have added joebloggs@email.com already.'

**Comment by JMurphyWeb** [comment]
Adding the confirm delete popup now

Deleting a signee will not affect any documents that are already in signing flow.

**Comment by JMurphyWeb** [comment]
added unique constraint to our table. Error message is a generic 'failed to add signee' but should be sufficient

**Comment by jonscottfilm** [comment]
Working.

Is this 'failed to add signee' for your backend, and not us? i.e. is this what enables the 'Are you sure?' message when deleting a signee?

**Comment by JMurphyWeb** [comment]
no the logic involved in the two steps are different. presenting an 'are you sure' message is not as easy adding possibly duplicate signees to a document

**Comment by jonscottfilm** [comment]
Right, so this prevents duplicated email addresses being used as project signees. Not sure this was working when we tested last night, but it is now!
