### ISSUE TITLE
Project details view

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#51]
As a project owner,
I can view a project that I have created,
so that I can review it's details as well as offers related to that project and links to edit the project

**Comment by JMurphyWeb** [comment]
Add styling to project details view.

**Comment by jonscottfilm** [comment]
This navigation needs thought, or at least convo with Jono, as I see #54 might reference the same issue?

- Dashboard lists projects as tiles showing key details and offers status. _(think this should be condensed to 2 lines, with offers to RHS, although I see it might be because the centralised text works well on mobile. Can be discussed as part of design issues)_
- Click project, navigates to full-screen-width view of that Project tile (#54 ?). Presume additional work will show full project details (capable of being edited) like currently seen here: https://karmaradio.herokuapp.com/projects/

Add create 'New Project' button to main dashboard view. Perhaps small underneath My Projects tile, i.e. not prominent as discussed verbally (can't find where, digitally!)

**Comment by JMurphyWeb** [comment]
@jonscottfilm we hope that navigation has now ironed out any problems you had here.

**Comment by jonscottfilm** [comment]
Working. Closing.

Will raise design comments in new issue.
