### ISSUE TITLE
PM can create an offer using the form

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#61]
A pm can view the create offer form and submit it to create an offer. They can enter a registered user or an unrecognised user.

see #8 for validation and required fields requirements.

**Comment by JMurphyWeb** [comment]
```elixir
      user -> # user is already registered
        project
        |> build_assoc(:offers)
        |> Offer.changeset(offer_params)
        |> Ecto.Changeset.put_assoc(:user, user)
```

Adds the project to the offer, then adds the user to the offer.

**Comment by JMurphyWeb** [comment]
#78 bug is listed in this issue

**Comment by jonscottfilm** [comment]
Offer Start Date should default to TODAY, (but not disable the ability to select historic date in event of creating contract retrospectively).

Something to add to Project defaults, later for sure:
Working Week - 5 Days (default, but can change per offer)
Currency - GBP (default, but can change per offer)
Sixth & Seventh Day Multipliers
I'll create an issue.

**Comment by jonscottfilm** [comment]
'!Can't be blank' errors for empty fields, eg box rental and equipment rental etc.. Think this is part of our conditional logic, yet to be applied, i.e. box rental value default value is 0.00, therefore no further box rental  fields appear, or are required to fill.

Many deals/offers will not include _any_ box or equipment.

![image](https://cloud.githubusercontent.com/assets/28431542/26305835/d506b356-3ee8-11e7-9537-625d4b295e18.png)

**Comment by jonscottfilm** [comment]
Also:

'Other Deal Provisions' - not 'required'.
Box rental period - should be number-only field
Equipment rental period - should be number-only field
Fee per day inc holiday - think we should HIGHLIGHT or capitalise DAILY in the label here, to remind PM

**Comment by jonscottfilm** [comment]
By TODAY, I mean 'TODAY FUNCTION' date, yeah?
i.e. date of whatever day the PM creates the offer, not always '22 May 20176' :)

**Comment by jonscottfilm** [comment]
We agreed to not have First Name & Last Name as part of the offer, and it not appear until entered into Start Pack by contractor. That is current working method.

My only issue with that (and it's exposure is minor) is, although target email is the unique identifier, there is no qualifying fields without the fullname also being present. 

_If_ the offer reaches it's intended recipient correctly, then Joe Bloggs knows it's his email, he's expecting the offer for Grip & all deal info as discussed.

_Should_ the offer be emailed to a 3rd party, eg an agent (our current method, for which 'target email' works), is they _could_ have multiple grips on their books, and confusion could occur, because there is no other unique identifier to differentiate between Grip 1, and Grip 2 who might have different start dates, and possibly rates.

_Also_ a back and forth 'amended offer' between contractor and PM, could result in confusion for the PM, when he's handling multiple offers, and he can only identify by email.

It also means the email offer, and amended offer, and any notification prior to completing Start Pack, is not personally addressed to the contractor - which I think is a nice, and effective way, of engaging the use in the app.

Sure this is a 'nice to have', Priority 4. I've created a new issue:

**Comment by JMurphyWeb** [comment]
Hey @jonscottfilm did you mean to re-open this issue? Please remember to link all issues back to their originator if applicable, which helps with navigation for future devs & you.

**Comment by JMurphyWeb** [comment]
ahh just seen the above comments https://github.com/karmaradio/karma/issues/61#issuecomment-303073395

Box rental period - should be number-only field
Equipment rental period - should be number-only field

These are currently text inputs as per spread sheet.

**Comment by jonscottfilm** [comment]
Hey @jmurphyweb. Well, only re-opened awaiting comment or resolution of points made about eg:

'Fee per day inc holiday - think we should HIGHLIGHT or capitalise DAILY in the label here, to remind PM'.

If you've implemented all, then it can be closed, yes.

**Comment by jonscottfilm** [comment]
Ah, sorry, you've seen it now.

**Comment by JMurphyWeb** [comment]
Should be done (added per diem) to the end as capitalising was more work than it seems! let's create an issue if you aren't happy with that

**Comment by jonscottfilm** [comment]
Ah, I see what's happened. Per Diem will be confusing. 
If we can't capitalise/bold the label like so: 'Fee **per day** including holiday'
then don't worry for now.

I'm afraid I do think the create/edit offer view needs separate sections, like how the deal get's presented to the contractor: Offer details, Fees, Allowances - for UX.  
New issue?

**Comment by jonscottfilm** [comment]
Needs correction of https://github.com/karmaradio/karma/issues/61#issuecomment-303758271 to complete, and close.

**Comment by jonscottfilm** [comment]
Amend field label to, in priority order:

1. 'Fee **per day** including holiday'
or
2. 'Fee PER DAY including holiday'
or
3. 'DAILY fee including holiday'

Then this can be closed.




then don't worry for now.

**Comment by JMurphyWeb** [comment]
https://github.com/karmaradio/karma/issues/61#issuecomment-303758271 new issue.

https://github.com/karmaradio/karma/issues/61#issuecomment-304013387 we'll fix in this one

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is now testable

**Comment by jonscottfilm** [comment]
Testing now.

Error flash/banner/colour needs to be implemented here, so it's more prominent:

![image](https://cloud.githubusercontent.com/assets/28431542/26624297/611b30a0-45e8-11e7-9e17-43b470c9013d.png)

**Comment by jonscottfilm** [comment]
Presume the styling, fonts & error message https://github.com/karmaradio/karma/issues/61#issuecomment-305130563 will be picked up by @nogainbar changes...? 

Field names/labels all corrected, thanks.

Only just noticed this, 'Fee per day inc holiday' and the '6 & 7 day multiplier' fields, should appear higher up the list, between 'Currency' and 'Other deal provisions.' Will create issue.

I'll create separate issue regarding _how_ the offer info is viewed/formatted, in view offer view.

Working. Closing.
