### ISSUE TITLE
Contractor - Receive Offer 

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#7]
As a contractor,
I should be able to receive offers,
So that I have the option of joining a project

**Comment by JMurphyWeb** [comment]
covered by dashboard issue #19

**Comment by JMurphyWeb** [comment]
@jonscottfilm offer should result in an email and an offer showing up on the dashboard once the user is signed up/logged in 🌮 🎉

**Comment by jonscottfilm** [comment]
As a NEW contractor, i.e. new to Karma, when I open the offer link I receive, I see this:

![image](https://cloud.githubusercontent.com/assets/28431542/26628447/1b41bcf8-45f6-11e7-975a-c9fbca1cafef.png)

2 points.

1. I'm not sure the red error is necessary, it's self explanatory that a log in screen needs me to log in. Not an error, as such.

2. New Issue, I am sure, but it would be good when the system _knows_ the user doesn't exist on the system yet, that the link takes them to the 'Create new account' page, rather than being hit with this error as their first experience of Karma.

**Comment by jonscottfilm** [comment]
Receive offer email is working.

View offer is not, for me: (could it be a consequence of multiple logins? Clear my browser cache? 

BTW - tried in Chrome incognito, same issue. Edge browser, couldn't load page, I had to insert s after http. Same issue - no permission to view project.

![image](https://cloud.githubusercontent.com/assets/28431542/26628856/af29c978-45f7-11e7-824d-5e9ede66e773.png)

**Comment by jonscottfilm** [comment]
Ok. So can't fully test yet, right?

**Comment by jackcarlisle** [comment]
Yeah that's right, haven't looked into this yet

**Comment by jonscottfilm** [comment]
Gotya

**Comment by JMurphyWeb** [comment]
@jonscottfilm regarding this: https://github.com/karmaradio/karma/issues/7#issuecomment-305154824 - at the moment, 
- if a new user receives an offer, they will get sent to the create account view.
- if an already registered user receives an offer, they will get sent to the offer view, which will ask them to login first. As a flow, that doesn't sound too jarring to me. What do you think?

looking into the lacking of permissions now.

**Comment by jonscottfilm** [comment]
Receive offer working. Closing.

(bug when rejecting #196)
