### ISSUE TITLE
Contractor Upload Documents

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#9]
As a contractor,
I want to have the ability to upload documents (passport scans, etc...),
So that I can submit all relevant information

**Comment by jonscottfilm** [comment]
Are we able to implement a file-size limit, or down-size on the fly? 
And limited file-types, pref make all as PDF on the fly.

Is there any method for checking the usable resolution of an uploaded image (pdf/pic/file) - i.e. a catcher to avoid submission of unusable scans?

**Comment by jackcarlisle** [comment]
@jonscottfilm yes there are methods we can use to limit both file size and type. Would need to do a bit of research into checking resolution. This could be linked to the file size in some way but need to look into it further

**Comment by JMurphyWeb** [comment]
<img width="743" alt="screen shot 2017-05-28 at 10 12 41" src="https://cloud.githubusercontent.com/assets/12638261/26527561/45cf6ff2-438e-11e7-8d68-f21d1738fc7e.png">

After uploading around 7 images in one request, it took over 18 seconds. I will look into performing these requests in parallel to bring time down

**Comment by JMurphyWeb** [comment]
@jonscottfilm this should be testable inside create/edit startpack views 😄

**Comment by jonscottfilm** [comment]
All works good, by the look of it.

One snag, PDF (tried different files) didn't give the thumbnail preview for me (in Chrome & also in Edge):

![image](https://cloud.githubusercontent.com/assets/28431542/26631160/b6ae99a8-4601-11e7-805e-e550a978293b.png)

And, interestingly, Word documents (even those not saved in Google Drive), get opened in same window, in Drive viewer. (which may be my browser pref, but FYI).

![image](https://cloud.githubusercontent.com/assets/28431542/26631535/529bbd7c-4603-11e7-8991-2a3d0c189245.png)

**Comment by jonscottfilm** [comment]
Essentially, it's working. Bar 'preview' thumbnails of non-image files. If unable to preview thumbnail, perhaps use PDF & .doc icons.

**Comment by JMurphyWeb** [comment]
do we want to allow  .doc items here? I would have guessed pdf and images only

**Comment by jonscottfilm** [comment]
Idiots will try to upload anything, typically fricking 'Pages' files, of their equipment inventory... And they're not smart enough to make PDF's.
I'd love to say image and PDF only, but we'd be crippling users.
Too hard to make PDF's on the fly, isn't it? Pagination might get screwed.

**Comment by JMurphyWeb** [comment]
@jonscottfilm for now we will only accept PDF, JPEG, PNG.

If someone attempts to upload anything else, we will report an error. 

Users will have to convert their pages to PDF before uploading. If it is a requirement to convert .doc files on the fly, it can be done, but not an insignificant amount of work so could you add an issue to the backlog

**Comment by JMurphyWeb** [comment]
I will start work on restricting filetype uploads now, and using the default .pdf thumbnail if someone does upload a pdf.

**Comment by JMurphyWeb** [comment]
![screen shot 2017-06-05 at 16 36 20](https://cloud.githubusercontent.com/assets/12638261/26790855/279bf278-4a0d-11e7-817a-433938c14536.png)

If a user uploads a pdf in the startpack, we will display the normal thumbnail

**Comment by jonscottfilm** [comment]
Needs Helper Text written under the field, warning of file-type restriction!

Understand it prob needs server-side gubbins in order to tell them it's a restricted file ONCE they've uploaded, but yet to hit submit...?!

PDF icon needs to be aligned with left edge of button and text above, and icon smaller.

Once uploaded, filename _used_ to show, thus knowing one had successfully uploaded the _correct_ file. Can that be re-implemented?

IF one uploads incorrect file, OR file-type, or in the wrong field (eg passport in box rental field) - we need ability to delete the wrong file. Rather than just replace.
(example, one might drunkenly upload a compromising photo of oneself, and not have another permitted file on one's iPad to replace it...........)

**Suggested solution -** allow any file type. preview thumbnails for image types. all other files show as purple file icon (smaller :)) no extension, i.e. just labelled FILE, not PDF, .doc etc.
IF we can put a say 10Mb size limit on it, that's the only restriction we need for now.

**Comment by jonscottfilm** [comment]
bar this #373 (& label removal) this can then be closed.

**Comment by jonscottfilm** [comment]
Oh, and #371 delete documents

**Comment by JMurphyWeb** [comment]
@jonscottfilm if other issues are open and are not bugs associated with this issue, then this one can be closed.

**Comment by jonscottfilm** [comment]
Working.
